// <auto-generated />
using System;
using GradesBlazorApp.AppContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GradesBlazorApp.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20250224062600_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.2");

            modelBuilder.Entity("GradesBlazorApp.Entities.Grade", b =>
                {
                    b.Property<int>("GradeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int>("Score")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StudentId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SubjectId")
                        .HasColumnType("INTEGER");

                    b.HasKey("GradeId");

                    b.HasIndex("StudentId");

                    b.HasIndex("SubjectId");

                    b.ToTable("Grades");

                    b.HasData(
                        new
                        {
                            GradeId = 1,
                            Date = new DateTime(2025, 2, 24, 14, 25, 59, 819, DateTimeKind.Local).AddTicks(363),
                            Score = 5,
                            StudentId = 1,
                            SubjectId = 1
                        },
                        new
                        {
                            GradeId = 2,
                            Date = new DateTime(2025, 2, 24, 14, 25, 59, 845, DateTimeKind.Local).AddTicks(3364),
                            Score = 4,
                            StudentId = 1,
                            SubjectId = 2
                        },
                        new
                        {
                            GradeId = 3,
                            Date = new DateTime(2025, 2, 24, 14, 25, 59, 845, DateTimeKind.Local).AddTicks(3377),
                            Score = 4,
                            StudentId = 2,
                            SubjectId = 1
                        },
                        new
                        {
                            GradeId = 4,
                            Date = new DateTime(2025, 2, 24, 14, 25, 59, 845, DateTimeKind.Local).AddTicks(3378),
                            Score = 3,
                            StudentId = 2,
                            SubjectId = 2
                        });
                });

            modelBuilder.Entity("GradesBlazorApp.Entities.Student", b =>
                {
                    b.Property<int>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("StudentId");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            StudentId = 1,
                            FirstName = "Иван",
                            LastName = "Иванов"
                        },
                        new
                        {
                            StudentId = 2,
                            FirstName = "Петр",
                            LastName = "Петров"
                        });
                });

            modelBuilder.Entity("GradesBlazorApp.Entities.Subject", b =>
                {
                    b.Property<int>("SubjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("SubjectId");

                    b.ToTable("Subjects");

                    b.HasData(
                        new
                        {
                            SubjectId = 1,
                            Name = "Математика"
                        },
                        new
                        {
                            SubjectId = 2,
                            Name = "Информатика"
                        });
                });

            modelBuilder.Entity("GradesBlazorApp.Entities.Grade", b =>
                {
                    b.HasOne("GradesBlazorApp.Entities.Student", "Student")
                        .WithMany("Grades")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GradesBlazorApp.Entities.Subject", "Subject")
                        .WithMany()
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("GradesBlazorApp.Entities.Student", b =>
                {
                    b.Navigation("Grades");
                });
#pragma warning restore 612, 618
        }
    }
}
